#!/bin/bash

die() { echo >&2 "$@"; exit 1; }
[[ $1 ]] || die "directory name?"

dest=data/$1; shift

rm -rf "$dest"
cp -a templates/root "$dest"
scripts/make-inputs -o "$dest/input/pat" \
	-Iignore-keys -Wonly-keys -Sgeneral-spatial-params.toml \
	--layer-index '[0, 1]' \
	--layer-shift '[[0, 0], [1/3, 2/3]]'

scripts/make-inputs -o "$dest/input/aba-rot" \
	-Iignore-keys -Wonly-keys -Sgeneral-spatial-params.toml \
	--layer-index '[0, 0, 1]' \
	--layer-shift '[[0, 0], [1/3, 2/3], [0, 0]]'

scripts/make-inputs -o "$dest/input/abc-rot" \
	-Iignore-keys -Wonly-keys -Sgeneral-spatial-params.toml \
	--layer-index '[0, 0, 1]' \
	--layer-shift '[[0, 0], [1/3, 2/3], [2/3, 1/3]]'

cp Shakefile-inner.hs "$dest/Shakefile.hs"
cp update-inner "$dest/update"
cp shake "$dest"
cp shakexc "$dest"
cp scripts/install "$dest"
ln -s ../../scripts "$dest"
