#!/usr/bin/env python3


import numpy as np
import yaml
import json

def main():
	import argparse
	parser = argparse.ArgumentParser(
		description='Extracts eigenvectors from band.yaml into more speedily-parsible json',
		epilog='output is [(band) [(3N cartesian) [real, imag]]]')

	parser.add_argument('INFILE', type=str, help='path to band.yaml')

	args = parser.parse_args()

	d = yaml.load(open(args.INFILE))

	bands = d['phonon'][0]['band']
	bands = np.array([b['eigenvector'] for b in bands])
	bands = np.array([b.reshape((-1,2)) for b in bands])

	print(json.dumps(bands.tolist()))

main()
