#!/usr/bin/env python3

# NOTE: this prepares data for 'dot'

import numpy as np
import yaml
import json

def main():
	import argparse
	parser = argparse.ArgumentParser(
		description='Extracts eigenvectors from band.yaml into more speedily-parsible json',
		epilog='output is [(band) [(3N cartesian) [real, imag]]]')

	parser.add_argument('INFILE', type=str, help='path to band.yaml')
	parser.add_argument('--all', action="store_true",
		help='do all kpoints, outputting a 4d array.'
		     ' (default behavior is to only do first)')

	args = parser.parse_args()

	d = yaml.load(open(args.INFILE))
	d = d['phonon']

	out = []
	for bands in d:
		bands = bands['band']
		bands = np.array([b['eigenvector'] for b in bands])
		bands = np.array([b.reshape((-1,2)) for b in bands])
		out.append(bands.tolist())

	if args.all:
		print(json.dumps(out))
	else:
		print(json.dumps(out[0]))

main()
