#!/bin/bash

# function wrapper so we can use return instead of exit which may kill the user's shell
__test_hex_cli_is_installed() {
	[[ "$0" != "/bin/bash" ]] && {
		echo >&2 "don't just run this file, source it!"
		return 1
	}
	# prefix PATH to beat the 'shake' binary that comes with the package
	{ ! which __hex_cli_is_installed.dummy >/dev/null 2>/dev/null; } && PATH=$(pwd)/scripts/cli:$PATH
	return 0
}

__test_hex_cli_is_installed
